### ISSUE TITLE
big-foot default background and color are both black

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#108]
We should probably add in a better default text color for content in the div.big-foot so that we don't get black on black text.

![screen shot 2015-09-23 at 10 28 40 am](https://cloud.githubusercontent.com/assets/295804/10052876/dff1a364-61dd-11e5-846e-2de3a0a7e159.png)

**Comment by rraub** [comment]
This might be a problem in the WordPress Theme, you can easily reproduce it by adding a text widget to the footer.

**Comment by idmontie** [comment]
Can you post the page or post the mark up for this here? I'll need to see the classes. Otherwise, I can just reproduce it myself.

**Comment by rraub** [comment]
![screen shot 2015-09-23 at 3 30 16 pm](https://cloud.githubusercontent.com/assets/295804/10060750/0c5fb6d2-6208-11e5-950d-84bd0c990397.png)
is that good enough?

**Comment by idmontie** [comment]
Great thanks.
