### ISSUE TITLE
Form inputs default to display: none; 

### ISSUE THREAD

**Issue by cordmata** [gios-asu/ASU-Web-Standards-Bootstrap#109]
Just curious as to why certain inputs using the standard bootstrap form classes are hidden by default?

See: https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/master/scss/_forms.scss#L262

**Comment by idmontie** [comment]
This should get documented some where, but it is so that Radio Buttons can be customized to look like this:

![image](https://cloud.githubusercontent.com/assets/412382/10260309/f65f2be2-6928-11e5-9e81-34a47ef38f29.png)


With this markup:

```
<div class="radio">
  <label>
    <input type="radio" name="test1" value="option1">
    <span class="outer-wrap"><i class="fa fa-circle"></i></span>
    Radio off
   </label>
</div>
```

**Comment by cordmata** [comment]
So the suggestion for those of us who want to use standard controls is to override with:

```
.radio {                
  input[type="radio"] { 
    display: block;     
  }                     
}                       
```
Wouldn't it be better to opt-into the non-standard controls rather than having to opt-into the native ones?

**Comment by idmontie** [comment]
It is supposed to be the default when using the web standards: https://publicservice.asu.edu/content/request-information-0, https://filmdancetheatre.asu.edu/degree-programs/film-degree/bachelor-of-arts-in-film, or http://asu-ws.29thdrive.com/ui-kit/standard-components/#forms

Not to say I don't agree with you, hiding the radio buttons most likely just confuses screen readers, but this aims to be as close to the Web Standards implemented by UTO.

**Comment by cordmata** [comment]
Right on. Good to know. I was coming from the point of view of someone treating this as simply a bootstrap theme, following their doc on components and styles. 

Just curious, is there canonical documentation on these standards somewhere besides https://hub.asu.edu/brand-hq/web-standards ?

**Comment by rraub** [comment]
@cordmata I wish there was more documentation on the standards, but from what I'm aware of there isn't much more besides some meeting notes in google docs. Really they are more like guidelines than standards. The 29th drive stuff was just a concept that they visually looked at and implemented separately. This repo has been a effort to consolidate the many different implementations, notes and feature requests into one isolated place. 

Rationalizing these styles is a worthy thing to do, so thanks for asking these questions.

I personally think the default should be to use the native radio buttons and opt-in to the "standard" ones.

**Comment by idmontie** [comment]
Heads up, these are documented in our online documentation. See [our forms documentation](http://gios-asu.github.io/ASU-Web-Standards-Bootstrap/section-forms.html)
