### ISSUE TITLE
look at potential conflicts with wtfforms in bootstrap 4

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#120]
Could our custom form styles be replaced with http://wtfforms.com ?

**Comment by idmontie** [comment]
Bootstrap 4 still has a lot of stuff up in the air. On hold until it is out of the alpha stage.

They also got rid of Glyphicons!

**Comment by idmontie** [comment]
Following up on this:

Why were we looking into wtfforms? Our version of the web standards already has styling for form elements.

What can be done is that the wtfform styles can be proposed and added to the [web standards](https://brandguide.asu.edu/web-standards) which has no official documentation on forms.

**Comment by idmontie** [comment]
Also, I'm going to vote to close this since there is no definitive end (or way to finish) to this issue.

What I will do though is make a branch where we update to Bootstrap 4 and check that the forms and our panels still work as expected. See #119

**Comment by rraub** [comment]
Agreed
