### ISSUE TITLE
Add testing for nav (both mobile and non-mobile)

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#136]
With all the similar but different mobile nav features we should really be testing the navigation menu.

**Comment by rraub** [comment]
@idmontie since you know how to change the browser width, I can help write the tests once we get the mobile test environment working.

**Comment by idmontie** [comment]
We can set custom launchers for the Karma Runner for our Grunt tests.

See https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/develop/Gruntfile.js#L92

So, we can make two different viewport sizes, but I think the visual tests have dependencies on the size of the viewport.

So... yes, possible, but the tests will have to be rewritten.
