### ISSUE TITLE
Add Bootstrap as a Bower dependency

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#149]
it would let us specify which versions of bootstrap this theme is compatible with.

**Comment by idmontie** [comment]
I'll have to try it and see how it effects the WordPress repo. I'm not sure if a dependency is the right way to do it. An `imply` sort of feature would be more what we want, but Bower doesn't have it.

**Comment by idmontie** [comment]
When trying to solve #119, the easiest way to do it was to make bootstrap a dependency. So, yup, we will make it at least a dev dependency.

**Comment by idmontie** [comment]
I will solve #119 first, and then make another PR that will be a WIP where the bootstrap dependency is set to 4.0^ to close out #119 and #120.

There are quite a bit of things we will need to fix for bootstrap 4.0. I will document them in the PR.
