### ISSUE TITLE
Do not use pixel values for font size

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Bootstrap#151]
Use ems and rems. Use 1rem at the root.

Check buttons too.

**Comment by idmontie** [comment]
Use rems. Fallbacks don't matter.

**Comment by idmontie** [comment]
We will need to **only** touch:
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/develop/scss/variables/_typography.scss

**Comment by rraub** [comment]
FYI we could use a sass function to help with the conversion:
```
@function pem($pixels) {
  @return #{$pixels/16.0}em
}
```
[source](http://blog.55minutes.com/2012/04/media-queries-and-browser-zoom/)

**Comment by idmontie** [comment]
Awesome :+1:

**Comment by rraub** [comment]
We need to look at more than just the variables scss files: 
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/0378a271aa5b8590167ec8937e499ffe04554af0/scss/_footer.scss#L24
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/73d2b901fcf57cbbef011ed9db0e64510fcf6c0e/scss/_profile.scss#L19
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/73d2b901fcf57cbbef011ed9db0e64510fcf6c0e/scss/_wells.scss#L29
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/73d2b901fcf57cbbef011ed9db0e64510fcf6c0e/scss/_calendar.scss#L108
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/73d2b901fcf57cbbef011ed9db0e64510fcf6c0e/scss/_calendar.scss#L114
https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/0378a271aa5b8590167ec8937e499ffe04554af0/scss/_mega-menu.scss#L114

**Comment by rraub** [comment]
and some others in scss/scaffolding/
