### ISSUE TITLE
New Standards for Mega Nav

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#191]
Apparently this page got updated recently: https://brandguide.asu.edu/web-standards/enterprise/navigation#quicktabs-primary_navigation=2

Looks like our big offenses are the vertical divider color, but there might be some other changes we need to consider to keep in line with the standard.

**Comment by nathan-rollins** [comment]
Additional discrepancies (as I come across them):

Default Nav Menu Caret:
  color: #666666;

Hover Caret:
  color: #EEEEEE;
