### ISSUE TITLE
Upgrade Modernizr

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#203]
We are more than a full version old and its not managed through Bower. 
We can still bundle it in our built JS files if we want to (its for connivence) if we include it as a devDependency in bower and build it manually.

**Comment by rraub** [comment]
Lets look at using https://github.com/sapegin/grunt-bower-concat if we start getting these assets from Bower.

**Comment by nathan-rollins** [comment]
We don't want to use Bower for Modernizr. Modernizr needs to be built to include only the tests that we actually use, and [grunt-modernizr](https://github.com/Modernizr/grunt-modernizr) will handle that for us. I guess we could use bower to pull down Modernizr and build from that (if we needed to pull a specific version), but grunt-modernizr works just fine pulling directly from the repo.

Now, I am looking to see if we can/should change anything else in our build process. Do we really need to include Modernizr, Moment, and Smooth Scroll here (in js/_vendor.js)? We are including some initialization calls to them in the /js/ folder. But just like Bootstrap is a dependency in the Wordpress Theme, I think we could move these dependencies over to the bower and grunt build config in .standards. This would keep dependency versioning together in a single location and build step.

**Comment by rraub** [comment]
closed in #233
