### ISSUE TITLE
Create an NPM package distribution for this repo

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#220]
In addition to a bower package an npm package might be easier for users.

**Comment by nathan-rollins** [comment]
NPM support is dropped in favor of Yarn.

**Comment by nathan-rollins** [comment]
We are moving to use Yarn exclusively and the yarn lock file instead of package-lock.json. Yarn provides backward support for the deprecated Bower project and our new Docker testing container uses Yarn by default.
