### ISSUE TITLE
Update Innovation footer logo (for 2017)

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#229]
Its larger and now has 2017 in it.

![best-college-2017](https://cloud.githubusercontent.com/assets/295804/18567535/7a2a1068-7b4d-11e6-950f-6740bea7b078.png)

Also we should resize this bad boy down to 144x144 to save on bandwidth.

**Comment by nathan-rollins** [comment]
Phil mentioned Friday that the dimensions of the new innovation logo is *not* supposed to be larger. It is going to be resized back to the old dimensions.
