### ISSUE TITLE
Captions for images

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Bootstrap#48]
How do we caption images other than a panel with some text in it?

**Comment by rraub** [comment]
Since there are no standards on this, we could use the [bootstrap default](http://getbootstrap.com/components/#thumbnails-custom-content)?

**Comment by idmontie** [comment]
http://tympanus.net/Development/HoverEffectIdeas/index2.html Goliath is pretty cool.

**Comment by idmontie** [comment]
Emailed Jill asking for clarification on this.  I think the bootstrap version looks fine:

![image](https://cloud.githubusercontent.com/assets/412382/6514014/8fd2ebee-c33c-11e4-938e-d74794b7d4fe.png)

**Comment by idmontie** [comment]
It's been a month and no updates.  Closing and suggesting the Bootstrap captions until otherwise told.
