### ISSUE TITLE
Use KarmaJS to run tests

### ISSUE THREAD

**Issue by idmontie** [gios-asu/ASU-Web-Standards-Bootstrap#65]
Currently we have tests run on a page that was manually created and needs to be updated whenever a new test file is made, we should see if we can use KarmaJS with grunt to automatically make this file.

The file that should be automatically made is `test/qunit/mobile-index.html`.

**Comment by rraub** [comment]
This sounds like a great idea.
related: [karma-runner/grunt-karma](https://github.com/karma-runner/grunt-karma)
