### ISSUE TITLE
side nav sub items are not clickable

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#73]
In the photo below only the "Upcoming Events" link works the others do not:

![screen shot 2015-03-11 at 1 31 10 pm](https://cloud.githubusercontent.com/assets/295804/6606192/0668388a-c7f3-11e4-84cc-f2f059f007cf.png)

And this isn't specific to a sidebar its the sidebar-nav class that breaks it. 

ping: @idmontie

**Comment by rraub** [comment]
Looks like a z-index issue, its [explicitly set to 1](https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/7a458ff2edc16b4a2240b3ad6fbc1cf4af243e1d/scss/_navs.scss#L509)

**Comment by idmontie** [comment]
Did the solution not work?

**Comment by rraub** [comment]
Nope, I had to comment out some more styles to get it working.

**Comment by idmontie** [comment]
We need to fix this AGAIN.

**Comment by idmontie** [comment]
For some reason the coding standards are failing on Travis, but not my machine.

**Comment by idmontie** [comment]
Updated this in the Wordpress Theme. Passed local test, will merge into master and test on production. If it works, I'll close this issue.

**Comment by idmontie** [comment]
It works!
