### ISSUE TITLE
Styles for the current nav menu item with no sub items is not defined

### ISSUE THREAD

**Issue by rraub** [gios-asu/ASU-Web-Standards-Bootstrap#95]
```current-menu-item``` has no styling, however ```current-menu-ancestor``` does. 

Basically pages without children don't show up as active when your on that page and pages with children do.

**Comment by idmontie** [comment]
Can you post a screenshot?

**Comment by rraub** [comment]
Webspark example menu, when on the styles & layouts page:
![screen shot 2015-07-24 at 3 03 22 pm](https://cloud.githubusercontent.com/assets/295804/8885507/2bbf0672-3215-11e5-97fc-96e735f4f9ef.png)
and on our engagement page: 
![screen shot 2015-07-24 at 3 03 53 pm](https://cloud.githubusercontent.com/assets/295804/8885518/3fa3afa8-3215-11e5-9340-62626dc11ee0.png)

Plus in the doc's we have styles defined for 'active' that don't match webspark. They look like this:
![screen shot 2015-07-24 at 3 04 52 pm](https://cloud.githubusercontent.com/assets/295804/8885523/5c8af0a4-3215-11e5-8258-43e7f3c89bf8.png)

**Comment by idmontie** [comment]
Looks like this should have been fixed.
